server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          #uri: file:///${user.home}\programming\git-local\
          default-label: master
          uri: https://github.com/agape1225/STUDY_MSA/tree/main/git-config-yml